@startuml
actor 交付
交付 -> 河图: 创建项目, 选择,配置产品,配置网络,工勘,保存项目配置
蓬莱 -> 蓬莱: 提供api生成项目版本包
note right : 使用项目id作为入参
蓬莱 -> 河图: 调用河图api获取产品信息
蓬莱 -> 蓬莱: 调用河图sdk,传入项目id,生成有巢,装机镜像所需配置文件
note right : 版本包使用uuid标识
蓬莱 -> 蓬莱: 生成非首节点装机镜像
蓬莱 -> 蓬莱: 生成版本包,目前仅包含项目化的控制台包和配置文件,其他centos, 创建vm所需镜像, yum源放在硬盘中
蓬莱 -> 蓬莱: 生成离线安装包,即首节点装机镜像,包含有巢所需配置文件,非首节点装机镜像
蓬莱 -> 蓬莱: 出盘(首节点镜像, yum源,非首节点镜像,保存至本地,同步至luna)
交付 -> 交付: 使用工具&脚本制作首节点安装盘(移动硬盘)
蓬莱 -> 蓬莱: 通过考包api拷贝在线安装包
note right : 传入版本包uuid,目的Ip和目录,将项目版本包拷贝到目的ip指定目录下
交付 -> 交付: 使用工具将首节点装机镜像制作u盘装机u盘
交付 -> 交付: 将首节点装机u盘插入首节点,启动u盘装机
交付 -> 交付: 首节点装机完成后,将包含yum源的硬盘插到服务器上,yum源挂到首节点目录下,手工将ansible脚本运行所需的目录挂在首节点目录下
交付 -> 交付: 在首节点上执行ansible脚本,启动系统初始化,安装bifrost, 注册节点, 装机和部署银河版本
@enduml