gantt
section 块存储
section 对象存储 

section 文件存储 pygfs
    公共模块: 
    master: active, a1, 2022-12-15, 2w
    chunkserver: active, a1, 2022-12-15, 4w
    client: active, a1, 2022-12-15, 2w
section 文件存储 gfs
    公共模块: 
    master: active, a1, 2022-12-5, 2w
    chunkserver: active, a1, 2022-12-5, 4w
    client: active, a1, 2022-12-5, 2w
section 表格存储 pybigtable
