@startuml
actor client
client -> chunkserver: grpc连接chunkserver, 如果连接失败,连接副门chunkserver
note right: 此时不存在数据拆分写入到多个chunkserver的情况, 需考虑磁盘空间不足, 无法append的情况
client -> chunkserver: 将数据写入所有副本chunkserver所在节点缓冲区
chunkserver -> chunkserver: 主副本写数据,生成index
chunkserver -> chunkserver: 通知其他副本按照index写入数据
chunkserver -> chunkserver: 所有副本server通知主server写入是否成功
chunkserver -> chunkserver: 所有副本server写入成功则主副本通知client写入成功
chunkserver -> chunkserver: 有副本写入失败在通知client写入失败
@enduml